#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-openssl \
    --without-caps \
    --disable-x11 \
    --disable-systemd-daemon \
    --disable-bluez5 \
    --disable-jack \
    --disable-avahi \
    --disable-gsettings \
    --disable-gtk3 \
    --disable-solaris \
    --disable-tests \
    --disable-nls \
    --disable-dbus \
    --disable-systemd-login \
    --disable-gstreamer \
    --disable-bluez5-ofono-headset \
    --disable-esound \
    --disable-oss-output \
    --disable-oss-wrapper \
    --disable-tcpwrap \
    --disable-manpages \
    --disable-lirc

# We disable the manpages, as they require a perl module.
make
make DESTDIR="$1" install
