#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DBUILD_SHARED_LIBS=ON \
    -DMZ_ZSTD=NO \
    -DMZ_ZLIB=NO \
    -DMZ_LZMA=NO

cmake --build   build
cmake --install build
