#!/bin/sh -e

patch -p1 < fix-W_EXITCODE.patch

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddocs=false \
    -Dgir=false \
    -Dfribidi=false \
    -Dicu=false \
    -Dvapi=false \
    -Dgnutls=false \
    -D_systemd=false \
    . output

ninja -C output
ninja -C output install
