#!/bin/sh

# Give Xorg setgid to /dev/input.
chown :input "$KISS_ROOT/usr/bin/Xorg"
chmod g+s    "$KISS_ROOT/usr/bin/Xorg"

cat <<EOF

NOTE: You must be a part of the [1maudio[m group
      for sndio to work.

EOF
